sonar.projectKey=plateforme-educative-2025
sonar.projectName=Plateforme Educative
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/migrations/**, **/static/**, **/media/**, **/.venv/**, **/env/**, manage.py

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
